BaseUrl= "http://masashisalvador57f.github.io/"
languageCode = "en-us"
Title= "NothingIsImpossibleIfOneDesires"
paginate = 5
DisqusShortname = "MasashiSalvador"
Copyright = "All rights reserved - 2017"
canonifyurls = true

[params]
  description = "MasashiSalvador's thoughts / ideas / notes"
  metadescription = "ReactJS, ReactNative, Swift, Kotlin, Golang, Ruby, Mathematics, Machine Learning"
  cover = "images/cover.jpg"
  author = "Masashi Salvador Mitsuzawa"
  authorlocation = "Tokyo, Japan"
  authorwebsite = "http://masashisalvador57f.github.io/"
  bio= "An software Engineer @ Tokyo"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "MasashiSalvador57f"
  twitterName = "MasashiSalvador"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "MasashiSalvador"